FROM log/php:latest

LABEL maintainer="materliu@gmail.com"

USER root
# Let the container know that there is no tty
ENV DEBIAN_FRONTEND noninteractive

RUN cp -r /usr/share/nginx/html /usr/share/nginx/html-bak

COPY . /usr/share/nginx/html
COPY conf/nginx /etc/nginx
COPY conf/supervisor/supervisord.conf /etc/supervisord.conf

ENV COMPOSER_ALLOW_SUPERUSER = 1
RUN cd /usr/share/nginx/html \
    && cp -r /usr/share/nginx/html-bak/vendor /usr/share/nginx/html/ \
    && php artisan config:clear \
    && php artisan cache:clear \
    && php artisan clear-compiled \
    && php artisan config:cache \
    && composer dump-autoload -o \
    && chown -R www-data:www-data /usr/share/nginx/html/storage \
    && mkdir -p /run/sshd

EXPOSE 80

ENTRYPOINT /usr/sbin/sshd \
    && sh /usr/share/nginx/html/start.sh \
    && sleep 9999999d